### ISSUE TITLE
Changing parameters

### ISSUE THREAD

**Issue by IronCaterpillar** [adigostin/mstp-lib#12]
How can I change the following parameters:
- Hello Time
- Forwarding Delay
- Max Age

**Comment by adigostin** [comment]
Have a look at the code in the "develop" branch. What you need is:

- STP_SetBridgeHelloTime (this is ignored in RSTP and MSTP, spec says so);
- STP_SetBridgeForwardDelay
- STP_SetBridgeMaxAge
Pay attention to the units. These functions are meant for SNMP usage, so the units are those required by MIBs.

**Comment by adigostin** [comment]
I added in a recent release library functions for setting these three parameters as well as TxHoldCount, so I'm closing this ticket.
